CREATE OR ALTER PROCEDURE SP_CONSULTA_EQUIPOS (
@VALOR NVARCHAR(255)
)
AS
BEGIN
	SELECT * FROM equipo WHERE (nombre LIKE '%'+ @VALOR +'%' OR director LIKE '%'+ @VALOR +'%' ) AND estado <> 'E';
END
GO;

CREATE OR ALTER PROCEDURE SP_CONSULTA_ACTAPARTIDOS (
@VALOR NVARCHAR(255)
)
AS
BEGIN
	SELECT * FROM ACTA_PARTIDO WHERE (nombre LIKE '%'+ @VALOR +'%' OR director LIKE '%'+ @VALOR +'%' ) AND estado <> 'E';
END
GO;


CREATE OR ALTER PROCEDURE SP_CONSULTA_AGENDAS (
@VALOR NVARCHAR(255)
)
AS
BEGIN
	SELECT * FROM AGENDA WHERE (nombre LIKE '%'+ @VALOR +'%' OR director LIKE '%'+ @VALOR +'%' ) AND estado <> 'E';
END
GO;


CREATE OR ALTER PROCEDURE SP_CONSULTA_SORTEOS (
@VALOR NVARCHAR(255)
)
AS
BEGIN
	SELECT * FROM AGENDA WHERE (nombre LIKE '%'+ @VALOR +'%' OR director LIKE '%'+ @VALOR +'%' ) AND estado <> 'E';
END
GO;

